<script type="text/x-magento-init">
    {
        "#custom-form": {
            "validation": {}
        }
    }
</script>

<form action="<?php echo $block->getFormAction() ?>" method="post" id="custom-form">
    <div class="field required">
        <label for="ticket_title"><?php echo __('Title'); ?></label>
        <input name="title" type="text" id="ticket_title" class="input-text" style="width: 350px" data-validate="{required:true}" /><br />
    </div>
    <label for="ticket_description"><?php echo __('Description'); ?></label>
    <input name="description" type="text" id="ticket_description" class="input-text" style="width: 350px" data-validate="{required:true}" /><br />
    <input type="submit" value="Inserir" class="action-submit">
</form>

<div class="table-wrapper">
    <table class="data table" id="tickets-table">
        <caption class="table-caption"><?php echo __('Tickets'); ?></caption>
        <thead>
            <tr>
                <th scope="col" class="col id"><?php echo __('Ticket'); ?> #</th>
                <th scope="col" class="col date"><?php echo __('Date'); ?></th>
                <th scope="col" class="col title"><?php echo __('Title'); ?></th>
                <th scope="col" class="col description"><?php echo __('Description'); ?></th>
                <th scope="col" class="col status"><?php echo __('Status'); ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php
                $lista_tickets = $block->getTicketCollection();

                foreach($lista_tickets as $item)
                {                    
                    $each_item = $item->getData();
            ?>
            <tr>
                <td data-th="Ticket #" class="col id"><?php echo $each_item['ticket_id']; ?></td>
                <td data-th="Date" class="col date"><?php echo $each_item['creation_date']; ?></td>
                <td data-th="Title" class="col title"><?php echo $each_item['title']; ?></td>
                <td data-th="Description" class="col description"><?php echo $each_item['description']; ?></td>
                <td data-th="Status" class="col status"><?php echo $each_item['is_active']; ?></td>
                <td data-th="Actions" class="col actions"> - </td>
            </tr>

            <?php                    
                }
            ?>        

        </tbody>
    </table>
</div>

<?php if ($block->getPagerHtml()): ?>
   <div class="toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>